### ISSUE TITLE
Can it be simplified as follows?

### ISSUE THREAD

**Issue by ghost** [oroshnivskyy/go-gin-aws-x-ray#2]
I think this repo is a implementation of "xray.Handler()", can it simplified as:
```
func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	srv := &http.Server{
		Addr:    "0.0.0.0:8080",
		Handler: xray.Handler(xray.NewFixedSegmentNamer("myApp"), r),
	}

	if err := srv.ListenAndServe(); err != nil {
		fmt.Println("gin start err:", err)
	}
}
```

**Comment by oroshnivskyy** [comment]
Hi!
You right, technically it's an implementation of xray.Handler, but it gives more flexibility. Your application may not need to collect traces for all requests. Or You may want to set xray middleware as second or third middleware in the chain.

**Comment by ghost** [comment]
> Hi!
> You right, technically it's an implementation of xray.Handler, but it gives more flexibility. Your application may not need to collect traces for all requests. Or You may want to set xray middleware as second or third middleware in the chain.

yes, thanks!
